### ISSUE TITLE
Feat: The Companion (Drone) Will Follow the Character

### ISSUE THREAD

**Issue by Josue19-08** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#49]
### Project Location and Setup:
This issue will be worked on in **Unity** by navigating to the following path: **Project > Assets > Scenes > DemoPrincipalScene**. Within this scene, three characters will be found in the hierarchy:

- `Crafter@RightFist`
- `Crafter@RightFist (1)`
- `Crafter@RightFist (2)`

Each of these characters should be assigned a drone that will follow them. The drones can be found in **Assets > PolygonSciFiCity > Prefabs > Props**. There are four available drones; select one for each character to ensure variety.

### Issue Details:

- **Drone Assignment**:
  - Choose a drone from the available options in **Assets > PolygonSciFiCity > Prefabs > Props** for each character in the hierarchy (`Crafter@RightFist`, `Crafter@RightFist (1)`, `Crafter@RightFist (2)`).

- **Movement and Animation**:
  - Implement movement for the drone to naturally follow the assigned character.
  - When the character is stationary, the drone should exhibit idle animations or movements to prevent it from appearing static (e.g., hovering movements, rotations, etc.).
  - The movement should be smooth and maintain a consistent distance from the character without abrupt changes.
  - A reference video will be provided to demonstrate the expected movement and behavior of the drones.

### Interaction and Behavior:

- **Follow Behavior**:
  - The drone must follow the character smoothly, without collisions or erratic movements.
  - Implement logic for the drone to adapt to changes in direction, speed, and stops initiated by the character.

- **Idle Behavior**:
  - When the character is stationary, the drone should transition to a natural idle state, such as gentle hovering, rotation, or small position adjustments to maintain a dynamic appearance.

### Objective:
The goal of this issue is to enhance visual immersion and interaction by having drones exhibit realistic behaviors while following their assigned characters. This will contribute to a more engaging and dynamic game environment, aligned with the futuristic and cyberpunk aesthetic of **Citizen of Arcanis**.

VIDEO: https://youtu.be/PZD0cuGEm44?si=HlHUKi39hFbcu5a8&t=81

**Comment by BrayanMQ** [comment]
Can I jump on this task?

To solve the issue, I will assign a unique drone prefab to each character in the scene and implement a behavior script to handle both following and idle states.

The follow behavior will use smooth interpolation (Vector3.Lerp) to ensure the drone maintains a consistent distance behind the character, with gradual rotation adjustments (Quaternion.Slerp) for natural movement. For the idle behavior, the drone will detect when the character is stationary and transition to hovering animations or subtle randomized movements to maintain a dynamic appearance.

A central script will combine these behaviors, switching between follow and idle states based on the character's movement, ensuring smooth transitions

**Comment by Josue19-08** [comment]
Yes sir, it’s yours. @BrayanMQ
