### ISSUE TITLE
Feat: Enemy NPC Reaction to Attack the Main Character

### ISSUE THREAD

**Issue by Josue19-08** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#50]
### Issue Description:
The objective of this issue is to add an enemy NPC to the **DemoPrincipalScene** that reacts to the main character when within a specified range. The NPC should pursue the character and, upon reaching them, execute an attack animation. This aims to enhance interaction and gameplay dynamics by introducing reactive enemy behavior.

### Location and Setup:
- An NPC must be added to the **DemoPrincipalScene**.
- Movement animations (running or walking) are already available in **Assets > ExplosiveLLC** and should be applied to the NPC when pursuing the character.
- The attack animation (strike) needs to be created from scratch and can be stored in **Assets > ExplosiveLLC**.
- The NPC should also have an idle state animation when not pursuing the character. This animation is already available and is the same used by the player when idle.

**Note**: A reference video will be provided to demonstrate the expected NPC behavior, including state transitions.

### Issue Details:

- **Player Pursuit**:
  - Implement logic for the NPC to detect the main character when within a specified range.
  - Once in range, the NPC should begin pursuing the character using running or walking animations as appropriate.
  - The movement should be fluid and adapt to the character's direction and speed.

- **Idle State Animation**:
  - When the NPC is not pursuing the character, it should enter an idle state using the provided animation that keeps the NPC naturally stationary.

- **Attack Animation**:
  - Create a custom attack (strike) animation for the NPC from scratch.
  - The animation should be executed when the NPC is close enough to the main character.
  - The attack animation should be consistent with the game's visual style and offer an engaging experience.

### NPC Behavior:

- **Detection and Pursuit**:
  - Implement a detection system for the NPC to react only when the character is within the specified range.
  - The NPC should follow the character until they reach them or the character moves out of range.

- **Attack**:
  - Once close enough, the NPC should stop and perform the created attack animation.
  - Transitions between movement, idle, and attack animations should be smooth and natural.

### Objective:
The purpose of this issue is to enhance gameplay by introducing enemy NPCs that react to the player's character. This adds a level of challenge and immersion consistent with the dynamic and cyberpunk style of **Citizen of Arcanis**.

VIDEO: https://youtu.be/4ye56mwY_FI?si=UY5OZeukcj40s0GN&t=542

**Comment by ShantelPeters** [comment]
Can I take care of this issue?

**Comment by Josue19-08** [comment]
@ShantelPeters Could you give me a description of how you would solve it?

**Comment by ShantelPeters** [comment]
To solve this issue @Josue19-08 
I will  add an NPC to the DemoPrincipalScene and implement detection logic to trigger pursuit when the player is within range.Then Use existing movement animations for pursuit and apply an idle animation when the player is out of range. 
i will then create a custom attack animation and trigger it when the NPC reaches the player ensuring smooth transitions between movement, idle, and attack states, using blend trees or state machines. Lastly i will test the behavior for fluid interactions and adjust as needed to ensure a seamless and engaging gameplay experience.

**Comment by Josue19-08** [comment]
Ok, it's yours. 👍🏽 @ShantelPeters
