### ISSUE TITLE
Feat: Market Window Redesign

### ISSUE THREAD

**Issue by Josue19-08** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#52]
### Issue Description:
The goal of this issue is to redesign the existing market window in the **DemoPrincipalScene** to make it more visually appealing and consistent with the cyberpunk aesthetic of the **Citizen of Arcanis** game. The design should adopt a neon style, with visual elements that convey an immersive and futuristic experience. The redesign should resemble the example shown in the attached image, maintaining the general structure but with an enhanced visual style.

### Location and Setup:
- This issue will be worked on in **Unity** by navigating to the following path: **Project > Assets > Scenes > DemoPrincipalScene**.
- The market window is located within a canvas called **ScreenSpaceCanvas**, and inside this canvas, there is a panel named **MarketPanel**.
- The goal is to redesign **MarketPanel** to resemble the design in the provided image.

### Redesign Details:

- **Visual Style**:
  - Use a neon-style design with a cyberpunk-inspired color palette, including vibrant tones and glowing elements contrasting with dark backgrounds.
  - Maintain consistency with the overall aesthetic of **Citizen of Arcanis**.

- **General Structure**:
  - The window should include sections for featured products, item listings, selected item information, and purchase options.
  - Implement UI elements such as buttons, text boxes, and sections in a visually attractive way consistent with the cyberpunk theme.

- **Interactivity**:
  - Interactive elements should provide visual feedback when selected, such as glow effects or color changes.
  - Ensure a smooth user experience with intuitive navigation between different market sections.

- **Visual Example**:
  - The design should resemble the provided image, with sections for "Trending Products," an item list, selected item details, and purchase options (including price and a buy button).
  - Consider adding visual enhancements that highlight interactive elements, such as subtle animations or hover effects.

### Objective:
The purpose of this issue is to create an attractive and well-designed market window that encourages players to explore and use the market system. The redesign should provide a memorable visual experience, consistent with the dynamic and cyberpunk style of **Citizen of Arcanis**.

![Example_1](https://github.com/user-attachments/assets/d503bbd5-4c68-4c34-8a1a-831087f4ab32)
![Example_2](https://github.com/user-attachments/assets/2d617bee-df75-49d4-8c51-4f04c41e24da)
![Example_3](https://github.com/user-attachments/assets/bb03ca2a-b185-40d0-93a0-fe48490e7173)
![Market](https://github.com/user-attachments/assets/88f51255-ae4f-4063-983d-ce41f67216c8)

**Comment by od-hunter** [comment]
Please can i be assigned this issue? This is my first time contributing to this ecosystem and I would love to be given the opportunity. I am a blockchain developer, and my experience includes html, css, react, javaScript, typescript, c#, solidity & Cairo.

To solve this issue I’ll take the following steps: 
1.⁠ ⁠To start, I’ll first locate the MarketPanel inside ScreenSpaceCanvas in DemoPrincipalScene.
2.⁠ ⁠⁠I’ll use neon-style UI materials and glowing effects (e.g., shaders for neon glow). Then create neon color palette with bright colors and dark backgrounds.
3.⁠ ⁠⁠I’ll implement EventTriggers for buttons and text for hover and click effects (e.g., color change or glowing on hover). I’ll use Button.onClick and Image.material to trigger glowing effects on interaction.
4.⁠ ⁠⁠I’ll use Animator for transitioning between market sections and smooth opening/closing animations and lastly I’ll test to ensure responsiveness with Canvas Scaler set to Scale With Screen Size and also test button interactions and smooth transitions for UX optimization.

Please assign me I’m ready to work.

**Comment by MildPXL** [comment]
I’d like to resolve this.

**Comment by MildPXL** [comment]
I would love the opportunity to take on the redesign of the market window in the DemoPrincipalScene. With my experience in UI/UX design and a strong eye for detail, I’m confident in creating an immersive, neon-style interface that aligns with the cyberpunk aesthetic of Citizen of Arcanis.You can view some of my designs here:https://www.figma.com/design/w1hKGSuYWk53Om4pYOoncE/Web3-Design-Works?node-id=0-1&node-type=canvas&t=c7CCQj8fLjFaUFz1-0.   Here’s also why I’m the right fit for this task:

Experience with Aesthetic Design:
I have a deep understanding of creating visually appealing interfaces, especially for sci-fi and cyberpunk-themed projects. I’ll ensure the redesign incorporates vibrant neon colors, glowing elements, and a futuristic feel, as outlined in the brief.

Interactive and Intuitive Design:
My approach prioritizes user engagement. I’ll enhance interactive elements with visual feedback like hover effects, glow animations, and smooth transitions to create a memorable user experience.

Lastly, I will ensure that the redesign aligns with the principle of UX

**Comment by Josue19-08** [comment]
@MildPXL Well, you can work on this issue.

**Comment by Josue19-08** [comment]
@od-hunter We would like you to apply this issue:
[https://github.com/SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd/issues/51](url)

**Comment by od-hunter** [comment]
> @od-hunter We would like you to apply this issue: [https://github.com/SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd/issues/51](url)

Hello ser @Josue19-08 , I clicked on the link you said I should apply to, but it’s empty, please help.

**Comment by Josue19-08** [comment]
@od-hunter Sorry.

https://github.com/SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd/issues/59
https://github.com/SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd/issues/58

You can apply to these, please describe how you would solve the problem.

**Comment by od-hunter** [comment]
> @od-hunter Sorry.
> 
> #59 #58
> 
> You can apply to these, please describe how you would solve the problem.

Hi @Josue19-08 , all done ser, please check.

**Comment by CristopherAguilar10** [comment]
hi @MildPXL, any update?

**Comment by amJoe-dev** [comment]
I'd love to give this a go.

**Comment by Josue19-08** [comment]
@amJoe-dev Well, you can work on this issue.

**Comment by Josue19-08** [comment]
hi @amJoe-dev, any update?

**Comment by Josue19-08** [comment]
@amJoe-dev 
Please make your respective PR, we need to review what you have done so far. Tomorrow is your last day of the ODHack.

**Comment by sebas11042** [comment]
@NwosuTy Is there a way to contact you by telegram?

**Comment by NwosuTy** [comment]
Okay I'd like to work on this issue

**Comment by NwosuTy** [comment]
Created new pull request, I guess that's all
