### ISSUE TITLE
Feat: Character Selection

### ISSUE THREAD

**Issue by Josue19-08** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#53]
# Character Selection

## General Idea of the Issue:
The goal of this issue is to create a character selection experience that allows the player to choose a Reborn Citizen from a list of predefined characters, focusing on visual presentation and immersive interaction. The player should be able to view the available characters, select the desired one, and assign a name. This process will not include attribute adjustments or additional customization; it will be solely focused on the visual selection of the character.

The interface should be visually appealing and consistent with the futuristic and cyberpunk style of **Citizen of Arcanis**, using elements located in **Assets > PolygonSciFiCity > Prefabs**. The characters themselves are found in **Assets > PolygonSciFiCity > Prefabs > Characters**. The aim is to create a specific character selection scene that resembles the design shown in the attached image (character selection image) in terms of structure, but not the design or aesthetics of the prefabs. Characters should be prominently displayed, with viewing options that allow for full model rotation. A window should be included to display the face or torso of the characters in a matrix-like arrangement (similar to the image), and clicking on a character in this list should change and display the selected full character. Additionally, a button labeled "Continue" should be included, with a design consistent with the theme.

When a character is selected and displayed, it should have an idle animation applied to present it in a natural state. The idle animation is already available and can be found in **Assets > ExplosiveLLC**. The selected character should be displayed similarly to the attached image, showing the character in a resting state.

### User Interface (UI) for Character Selection:
- Display a list of predefined characters for the player to view and select.
- The visual presentation should be modern and eye-catching, reflecting the cyberpunk and futuristic world of the game.
- The interaction should be intuitive, allowing the player to easily select a character and receive visual feedback, such as highlighting or animations when a character is selected.
- The player should have the option to edit the name of the selected character before confirming their choice.

### Interaction and Navigation:
- Provide a preview of the selected character with viewing options such as 3D rotation.
- The matrix-like list should allow the player to explore different characters with a click, changing the main display to the selected character.
- Include a "Continue" button that allows the player to confirm their selection and proceed. The button's design should be consistent with the cyberpunk theme of the game.

### Idle Animation:
- When a character is selected, apply the idle animation to present it in a natural state. This animation can be found in **Assets > ExplosiveLLC**.
- The character should be displayed in a manner similar to the attached image, showing it in a resting or idle state.

## Visual Inspiration:
- The character selection scene should have a design similar to the attached image, with a futuristic presentation, lighting, and visual elements that convey the atmosphere of **Citizen of Arcanis**. *(Image of structures)*
- **Note on design**: We are not seeking a design as complete or advanced as the images shown, but it should still be attractive. However, there will be rewards if you wish to create it in a way that closely resembles the images.

## Purpose of the Issue:
This issue aims to offer a visually appealing and well-designed introductory experience that motivates the player to immerse themselves in the game world. Character selection should be a memorable process, where the presentation and interaction reflect the quality and atmosphere of **Citizen of Arcanis**.

![Character_Selection](https://github.com/user-attachments/assets/ca7df664-8037-442a-8a95-77549949b796)
![Structures](https://github.com/user-attachments/assets/52ac0a2a-77f7-41ee-9e99-22468c055847)

**Comment by NwosuTy** [comment]
Weird question but I'm guessing the design template in the image isn't available right, cause I could do this programmatically, where I'd struggle is with the design I'm not an artist

**Comment by NwosuTy** [comment]
I'd be able to implement the functions stated, but I'd like to know if you have the designs and models or would i have to create them myself, as I must say I'm not a good artist

**Comment by Josue19-08** [comment]
@NwosuTy We have all the structures (walls, floors, objects, characters, etc.). The task would be to create a scene with them.

**Comment by NwosuTy** [comment]
Alright then id love to help out

**Comment by Josue19-08** [comment]
Ok, it's yours @NwosuTy

**Comment by NwosuTy** [comment]
Good day, i have been trying to clone and fetch the repo for the last few days, and i keep getting a "you dont have access error"

**Comment by Josue19-08** [comment]
GM
Initially you must create your fork, you must follow the guide defined in the README.

If the error persists, do not hesitate to write to me by telegram
@Josue1908Cr

**Comment by CristopherAguilar10** [comment]
hi @NwosuTy, any update?

**Comment by NwosuTy** [comment]
I'm yes, although my progress has been delayed cause I had to focus on work related issues, I've been able to create the selection menu system, as well as a class that stores each character and now the idle animation and rotation of transforms, I'm currently fixing potential bugs and cleaning up the system, should have the complete project update pushed by Sunday

**Comment by Josue19-08** [comment]
@NwosuTy Could you show me a little of the progress you have made so far. Please

TG @Josue1908Cr

**Comment by sebas11042** [comment]
hi @NwosuTy how are you doing with the issue?

**Comment by NwosuTy** [comment]
I'm done, I'd be making the push any moment from now, I just need to get the accurate unity editor to avoid bugs

**Comment by Josue19-08** [comment]
@NwosuTy 
Please make your respective PR, we need to review what you have done so far. Tomorrow is your last day of the ODHack.

**Comment by NwosuTy** [comment]
Made the pull request, please review and get back to me
