### ISSUE TITLE
Enhancement: Organize subfolders in Demo_Scene

### ISSUE THREAD

**Issue by CristopherAguilar10** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#55]
Currently, the objects in the `Demo_Scene `scene are disorganized, which makes navigation and editing within the project difficult. It is necessary to create subfolders to categorize the scene elements.
![image](https://github.com/user-attachments/assets/43ac8794-1ae7-4ddf-9d29-bd2f8850b2ea)

**Tasks:**

1. Create the following subfolders in the project hierarchy:
- Vehicles: For vehicles used in the scene.
- Buildings: For architectural structures.
- Signs: For signs, road signs, etc.
- Props: For small interactive or decorative objects.
- Environment: For elements of the environment, such as lights, effects or sky.
2. Move the corresponding objects to their respective subfolders.

![image](https://github.com/user-attachments/assets/695fae4a-596d-4549-8518-1c46d8a8d7e0)

**Comment by mimisavage** [comment]
I'd be happy to work on it.

**Comment by BraCR10** [comment]
Hello maintainers I am BRACR10 a contributor of Dojo Coding, I would like to organize the code correctly, I have experience with object oriented programming and C#.
