### ISSUE TITLE
Feat: Create a main menu

### ISSUE THREAD

**Issue by CristopherAguilar10** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#56]
The project needs a basic main menu for players to start the game.

**Requirements:**
Buttons:

- “Play”: Load the Character Selection scene(DemoSelectionCharacter).
- “Options”: Placeholder for future configurations (can be disabled).
- “Exit”: Close the application.

**Basic design:**

- Simple background with the game logo.
- Stylized buttons to be functional.

**Functionality:**

- Use simple scripts to handle button events (load scenes, close game, etc.).

**Comment by 0xNgoo** [comment]
Can I handle this task?

**Comment by LeonM95** [comment]
Hello,

My name is Leo, and I'm a junior software developer from Costa Rica. This will be my first Hackathon, and I am excited to apply for this issue.

I have experience working with C#, JavaScript, Node.js, and some TypeScript. I believe this issue will be a fantastic opportunity to enhance my coding skills.

Currently, I am also learning about Web3 technologies.

Thank you for considering my application.

Best regards,  
Leo

**Comment by od-hunter** [comment]
Please can i be assigned this issue? This is my first time contributing to this ecosystem and I would love to be given the opportunity. I am a blockchain developer, and my experience includes html, css, react, javaScript, typescript, c#, solidity & Cairo.

To solve this issue I’ll take the following steps: 
1.⁠ ⁠After getting the UI components, I’ll create Panel/Image for the background. Then I’ll add 3 Buttons: Play, Options, and Exit.
2.⁠ ⁠⁠Next, I’ll attach SceneManager for scene loading. Then I’ll implement methods for button actions such as: OnPlayButtonClicked() to use SceneManager.LoadScene("DemoSelectionCharacter") to load the character selection scene, OnOptionsButtonClicked() logs a placeholder message for future features and OnExitButtonClicked() to use Application.Quit() to close the game.
3.⁠ ⁠⁠Then in the Inspector, I’ll link each button’s On Click() event to the respective methods in MainMenuController.
4.⁠ ⁠⁠Lastly, I’ll test to ensure the target scene is added to Build Settings.

Please assign me I’m ready to work.

**Comment by Yunusabdul38** [comment]
I’d like to work on this,
and make sure it meets the requirements

**Comment by CristopherAguilar10** [comment]
sure @0xNgoo, if you have any questions, please feel free to reach out to us
