### ISSUE TITLE
Documentation: Documenting Codes in the Scripts Folder

### ISSUE THREAD

**Issue by CristopherAguilar10** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#57]
The code in the Scripts folder needs documentation to improve its understanding and facilitate collaboration with other developers.

![image](https://github.com/user-attachments/assets/1cd3bf3c-3d1d-41d3-9859-419855012424)

**Tasks:**

1. Add XML comments to methods, classes and public variables.

- Example:
```csharp 
/// <summary> 
/// Controls the movement of the player.
/// </summary> 
/// <param name=“speed”>Speed of the movement.</param> 
void MovePlayer(float speed) { // Implementation here }
```

2. Document the general functionality of each script:

- What the script does.
- Where and how it is used.

**Comment by martinvibes** [comment]
May I try my hand at this? I have done some merged  docs for other repos 
It would be my first time on this repo
Kindly assign :)

**Comment by pheobeayo** [comment]
May I handle this issue?

I am a web3 frontend developer and Technical writer. I have successfully contributed to projects on the OnlyDust platform, writing Cairo, and Rust codes, cleaning up the codebase and properly documentating the codes. 

I will tackle this issue by going through the documentation properly, studying the script codes, understanding the codes, understanding the functions and writing out the functions in the proper documentation for better understanding of developers and users.

**Comment by BraCR10** [comment]
Hello maintainers I am BRACR10 a contributor from Dojo Coding, I would like to take the documentation of those scripts, I have experience with object oriented programming and C#. Before requesting the issue I looked the scripts and the without problems could comment them properly with XML format.

**Comment by CristopherAguilar10** [comment]
Hi @josephpdf, I assign you, if you have any questions I will be glad to help you.

**Comment by od-hunter** [comment]
Hi, can I be assigned this please? I am a blockchain developer and I'm also good at documentations. I'll come up with a documentation that will improve understanding and facilitate collaboration with other developers. I'll also add XML comments to methods, classes and public variables and document the general functionality of each script such as "what the script does" and "where and how it is used".

Below are some of the documentations I've done that were merged:
https://github.com/dojoengine/book/pull/308,
https://github.com/keep-starknet-strange/joyboy/pull/143,
https://github.com/Scaffold-Stark/ss2-docs/pull/31,
https://github.com/horuslabsio/Starknet-Scaffold/pull/94,
https://github.com/Hyle-org/examples/pull/15.

Please I’m ready to work, assign me please.

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics.

step on how to solve this issue 
I will take my time to understand the script code and document it in the code or create a script.md file to better understand the code by any developer using my project documenting skill to stat what it does and how it is used, which I can say is one of my habits when seeing large codebases.

will be glad to work on this 
Thanks

**Comment by NueloSE** [comment]
Am a technical writer with experience in documenting code base 

previous work done that is exactly same as the [bytebeast doc script](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/pull/104)

Can I contribute to this one?
ETA <= 2days
