### ISSUE TITLE
Implement Weapon Integration with Existing Inventory System

### ISSUE THREAD

**Issue by sebas11042** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#58]
This issue will be worked on in Unity by navigating to the following path: Project > Assets > Scenes > DemoPrincipalScene. The weapon model to be implemented can be found in Assets > PolygonSciFiCity > Prefabs > Weapons. 

![Issue implementacion arma](https://github.com/user-attachments/assets/a73de5de-ca9c-4909-a933-d6715fdd2484)

The inventory system currently in use is the Devion Games Inventory System, which has predefined mechanics for managing items in the game. Documentation and video tutorials for the inventory system can be found here: [Devion Games Inventory System Tutorials]
https://www.youtube.com/@Zerano100/videos

### **Weapon Selection and Setup:**

Choose one of the weapon models available in PolygonSciFiCity > Prefabs > Weapons for integration. Ensure the model is optimized for use with the character.

![Captura de pantalla 2024-11-20 214940](https://github.com/user-attachments/assets/b3bcc3ea-77d5-4936-b487-e0b98d4f7fce)

Set up the weapon as a pickable object in Unity, ensuring it is interactable by the player.

### **Inventory Integration:**

Add the weapon as an item in the Devion Games Inventory System, with appropriate metadata such as:

Item Name: (e.g., "SciFi Rifle").
Icon: Generate or use an icon that visually represents the weapon.
Description: (e.g., "A futuristic rifle designed for advanced combat").
Item Type: Weapon.
Ensure the weapon can be:
Picked up from the ground using the interaction key F.
Stored in the inventory as an individual item.
Dropped back into the game world from the inventory.
Equipping the Weapon:

### **Implement logic to equip the weapon to the active character.**
Position the weapon in the character's hand when equipped, ensuring proper alignment and orientation.
Configure animations (if available) or placeholders to simulate holding the weapon.
Interaction Logic:

The weapon should be interactable when dropped in the environment, allowing the player to pick it up again.
Use Unity's Collider and Rigidbody components to enable physical interaction.

The goal of this issue is to integrate a weapon into the existing inventory system, allowing players to interact with it naturally (pick up, store, equip, and drop). This feature will enhance gameplay by providing dynamic interactions and aligning with the futuristic, cyberpunk aesthetic of Citizen of Arcanis.

### **Acceptance Criteria:**

The player can pick up the weapon using the F key.
The weapon is stored in the inventory with an appropriate icon and metadata.
The player can equip the weapon, which appears in the character's hand when selected.
The weapon can be dropped from the inventory, becoming an interactable object in the game world.

### **How to Apply**
Follow the [README](https://github.com/SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd/blob/main/README.md)
 outlined in the README file.
If you have any questions or need assistance along the way, feel free to tag me at @sebas11042 🚀🔥
We can’t wait to see your magic in action! 😎✨

**Comment by mimisavage** [comment]
I'm really interested in this task, I'd love to contribute

**Comment by sebas11042** [comment]
Hello @mimisavage We will only accept requests that come from the only dust platform

**Comment by ShantelPeters** [comment]
May I try my hand at this?

**Comment by od-hunter** [comment]
Hi @sebas11042 , please can I be assigned this issue?

**Comment by sebas11042** [comment]
> Hi @sebas11042 , please can I be assigned this issue?
> 
> To solve this issue I’ll navigate to Assets > PolygonSciFiCity > Prefabs > Weapons and add Collider and Rigidbody components to the weapon prefab and save it as a reusable prefab. Next I’ll register weapon in Devion Inventory Manager (Item Name, Icon, Description, ItemType = Weapon) and use InventoryManager.AddItem() for adding and InventoryManager.RemoveItem() for dropping. Lastly, I’ll test.
> 
> Kindly assign me please, I’m ready to work.

Hi @od-hunter, its yours!

**Comment by sebas11042** [comment]
hello @od-hunter, are you working?

**Comment by od-hunter** [comment]
> hello @od-hunter, are you working?

Yes ser, will push a pr soon please 🙏🏻

**Comment by od-hunter** [comment]
Hi @sebas11042 , I have a question, please how does the weapon get randomly spawned in the environment during sessions?

Are there any existing systems for that or am I to create a new one?
