### ISSUE TITLE
Implement Swords in the Inventory and Equip Them to the Character

### ISSUE THREAD

**Issue by sebas11042** [SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd#59]
### **Project Location and Setup:**
This issue will be worked on in Unity by navigating to the following path:
Project > Assets > Scenes > DemoPrincipalScene.
The sword models to be used can be found in:
Assets > PolygonSciFiCity > Prefabs > Weapons.

![Issue implementacion arma](https://github.com/user-attachments/assets/e40e3d6d-1004-4301-9949-9969a6ecb656)

The inventory system currently implemented is the Devion Games Inventory System. This system will be used to manage the swords as interactive items in the game. Documentation and tutorials can be found here:
[Devion Games Inventory System Tutorials](https://www.youtube.com/@Zerano100/videos).

### **Issue Details:**

**Sword Selection and Setup:**
Select one or more sword models from PolygonSciFiCity > Prefabs > Weapons for integration into the inventory.

![Es](https://github.com/user-attachments/assets/5df1a699-96a2-478d-8cdc-e9c065b2c058)

Configure each sword as an interactive object that the player can pick up from the environment.
Inventory Integration:
Add the swords to the Devion Games Inventory System with the following metadata:
Item Name: (e.g., "Luminous Sword").
Icon: Create or use an icon to represent each sword visually.
Description: (e.g., "A futuristic sword emitting a bright electric blue glow").
Item Type: Weapon.
Ensure that the swords can:
Be picked up from the ground using the F key.
Be stored in the inventory with their respective names and icons.
Be dropped back into the game world from the inventory.

### **Equipping the Swords:**
Implement logic to allow the swords to be equipped by the active character.
Position the equipped sword in the character's hand, ensuring proper alignment and orientation.
Configure placeholders or animations to display the character holding the sword.
Interaction Logic:
The swords should be interactable when dropped into the environment.
Use Unity's Collider and Rigidbody components to enable physical interaction.

### **Objective:**

The objective of this issue is to integrate swords into the existing inventory system, allowing players to pick them up, store them, and equip them to their character. This feature will enhance immersion and provide dynamic interactions that align with the futuristic, cyberpunk aesthetic of Citizen of Arcanis.

### **Acceptance Criteria:**

The player can pick up swords from the ground using the F key.
The swords are correctly stored in the inventory with their icons and metadata.
The player can equip the swords, and they appear in the character's hand properly aligned.
The swords can be dropped from the inventory, reappearing in the world as interactive objects.

### **How to Apply**

Follow the [README](https://github.com/SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd/blob/main/README.md) outlined in the README file.
If you have any questions or need assistance, feel free to tag me at @sebas1104 🚀🔥
We’re excited to see your work in action! 😎✨

**Comment by mimisavage** [comment]
@sebas11042 
 This aligns with my skills and experience, l'd be happy to work on it.

**Comment by od-hunter** [comment]
Hi @sebas11042 , can I work on this issue please?

**Comment by sebas11042** [comment]
> I’m interested in this one.
> 
> I'll configure the sword models as interactive objects, allowing players to pick them up with the F key. Then, I'll integrate them into the Devion Games Inventory System with the necessary metadata. I'll implement logic for equipping the swords, ensuring they align correctly in the character's hand, and make sure they can be dropped and interactable in the world.
> 
> I'm a new contributor to this repo, can i be allowed to take this isssue?

Yes of course, if you have questions you can write to me!

**Comment by NwosuTy** [comment]
Has this been solved

**Comment by KevinMB0220** [comment]
@NwosuTy If you want apply for this Feat: Market Window Redesign #52
